version: '2'

services:
  elasticsearch:
    image: elasticsearch:5.6.13
    restart: always
    ports:
      - 9200:9200

  logstash:
    build: ./logstash
    restart: always
    ports:
      - 5044:5044
    links:
      - elasticsearch

  kibana:
    image: kibana:5.6.13
    restart: always   
    environment:
      ELASTICSEARCH_URL: http://172.17.0.1:9200
    links:
      - elasticsearch
    ports:
      - 5601:5601

  filebeat:
    build: ./filebeats
    restart: always
    ports:
      - 5045:5044